/** About / Operator column portrait. */
export const ABOUT_OPERATOR_IMAGE_SRC = "/about-operator.png";

export const TRANSLATIONS = {
  en: {
    header_arch: "Creative Archive",
    header_loc: "Based in Istanbul / Global",
    header_idx: "Index: 2024.11.X",
    nav_works: "Works",
    nav_about: "About",
    nav_contact: "Contact",
    nav_services: "Services",
    nav_logo_aria: "MADBAK — scroll to top",
    nav_primary_aria: "Primary navigation",
    nav_lang_aria: "Language",
    nav_menu_toggle: "Menu",
    nav_close_menu: "Close menu",
    nav_section_label: "Index",
    nav_home: "Home",
    nav_works_categories_aria: "Works categories",
    works_archive_crumb: "MADBAK / ARCHIVE",
    works_scroll_cue: "Scroll to explore",
    works_next_category: "Next category",
    works_back_to_works: "Back to works",
    works_all_works: "All works",
    works_live_website: "LIVE WEBSITE",
    works_view_project: "View Project",
    works_visit_project: "VISIT PROJECT",
    works_cta_live: "LIVE",
    works_view_on_foundation: "View on Foundation",
    works_explore: "Explore",
    works_close: "Close",
    works_next: "Next",
    works_previous: "Previous",
    works_character_study: "01 / 01 · character study",
    works_moving_identity: "01 / 01 · moving identity",
    works_nft_kicker: "Foundation / 1 of 1",
    works_nft_heading: "ON-CHAIN",
    works_nft_intro:
      "A collection of independent digital pieces, each with its own page for viewing and minting.",
    works_project_archive: "PROJECT ARCHIVE",
    works_selected_digital: "SELECTED",
    works_digital_works: "DIGITAL WORKS",
    works_archive_websites_desc:
      "A curated archive of digital products, cultural platforms, and interactive web experiences.",
    works_archive_character_heading_1: "CHARACTER",
    works_archive_character_heading_2: "STUDIES",
    works_archive_character_desc:
      "Character exploration, styling, silhouettes, and narrative visual systems.",
    works_archive_influencer_heading_1: "SYNTHETIC",
    works_archive_influencer_heading_2: "PERSONA",
    works_archive_influencer_desc:
      "Digital identity systems, generative look development, and campaign imagery for synthetic talent.",
    works_archive_nft_heading_1: "ON-CHAIN",
    works_archive_nft_heading_2: "EDITIONS",
    works_archive_nft_desc:
      "Independent digital editions and collectible visual systems linked to their mint pages.",
    works_discipline: "Discipline",
    works_year_label: "Year",
    works_status_label: "Status",
    works_in_development: "In Development",
    hero_dev: "FRONTEND DEVELOPER • WEB DESIGNER",
    hero_scroll: "Scroll to explore",
    work_title: "Selected Works",
    about_op: "Operator",
    about_h1_1: "DESIGNED",
    about_h1_2: "PRESENCE",
    about_intro_before: "I’M BABAK, WORKING UNDER THE NAME ",
    about_intro_after: ".",
    about_p2:
      "I’m a frontend developer and mostly build interactive, complex websites, using React and Next.js for development and GSAP and Three.js for animation.",
    about_p3:
      "My work covers full website builds for businesses and various projects, including a few Web3 ones, and lately I’ve been working on AI-assisted automation to speed up my workflow.",
    about_p4:
      "My background in design still shows up in my work too, including a few more visual pieces like character design and some on-chain work, which are more of a creative outlet.",
    about_p5:
      "Based in Istanbul, working freelance with clients around the world. If you’ve got a frontend development project in mind, I’d love to hear about it.",
    about_operator_image_alt:
      "Portrait of Babak Ravanbakhsh, creative frontend developer known as Madbak",
    stat_role: "Role",
    stat_stack: "Stack",
    stat_engine: "Engine",
    stat_loc: "Location",
    val_role: "Frontend Developer",
    val_loc: "Istanbul / Global",
    man_defy: "Defy",
    man_conv: "CONVENTION",
    man_p:
      "MADBAK exists at the intersection of raw brutality and high-end digital precision. We build interactive architectures that challenge the generic web.",
    man_re: "Render Engine",
    man_phys: "Physics",
    man_grid: "Grid System",
    man_stat: "Status",
    man_aes: "Aesthetic Nominal",
    game_proto: "System Protocol // Mini Game",
    game_sys: "System",
    game_dec: "Decryption",
    game_desc1:
      "Tap the node to inject packets — a small interactive sketch.",
    game_desc2: "That’s the whole thing. Thanks for playing.",
    game_btn1: "Inject",
    game_btn2: "Nothing happens :)",
    game_tap: "Tap Fast",
    game_prog: "Progress",
    game_log_1: "Injecting…",
    game_log_2: "Decrypting…",
    game_log_3: "Signal received…",
    game_access: "ACCESS GRANTED",
    game_complete_sub: "DECRYPTION COMPLETE",
    game_surprise_fail: "SYSTEM FAILURE",
    game_surprise_access: "ACCESSING CORE…",
    foot_ready: "System Ready",
    foot_init: "Contact",
    foot_send: "Send Data",
    foot_blurb:
      "Madbak — creative frontend developer and web designer building interactive websites, digital experiences, and motion-led projects.",
    foot_explore_works: "Explore works",
    works_archive_link: "Open archive",
    modal_active: "Dataset Active",
    modal_type: "Type",
    modal_year: "Year",
    modal_role: "Role",
    modal_tech: "Tech",
    modal_context: "Context",
    modal_sim: "Simulation Offline",
    work_sub1: "04 — Selected",
    work_sub2: "Creative · Digital editions",
    work_h1: "SELECTED",
    work_h2: "WORKS",
    work_desc:
      "A curated selection of digital creations — high-end visuals, sharp metadata, and immersive experiences.",
    view_details: "View Gallery",
    nft_sub1: "05 — Digital Assets",
    nft_sub2: "On-Chain · Verified",
    nft_h1: "NFT",
    nft_h2: "COLLECTION",
    contact_label: "[004] CONTACT",
    contact_title_1: "LET'S CREATE",
    contact_title_2: "TOGETHER",
    contact_commissions:
      "Open to select freelance projects and creative collaborations",
    contact_rights: "© 2026 MADBAK. All rights reserved.",
    contact_available: "Currently Available",
    contact_social_x: "X",
    contact_social_ig: "Instagram",
    contact_social_tg: "TELEGRAM",
    contact_social_wa: "WHATSAPP",
    contact_social_li: "LinkedIn",
    contact_social_gh: "GitHub",
    nft_view: "View Asset",
  },
  fa: {
    header_arch: "آرشیو خلاق",
    header_loc: "مستقر در استانبول / جهانی",
    header_idx: "شاخص: ۲۰۲۴.۱۱.X",
    nav_works: "آثار",
    nav_about: "درباره من",
    nav_contact: "تماس",
    nav_services: "خدمات",
    nav_logo_aria: "MADBAK  بازگشت به ابتدای صفحه",
    nav_primary_aria: "ناوبری اصلی",
    nav_lang_aria: "زبان",
    nav_menu_toggle: "منو",
    nav_close_menu: "بستن منو",
    nav_section_label: "فهرست",
    nav_home: "خانه",
    nav_works_categories_aria: "دسته‌بندی آثار",
    works_archive_crumb: "MADBAK / آرشیو",
    works_scroll_cue: "برای مشاهده اسکرول کنید",
    works_next_category: "دسته‌بندی بعدی",
    works_back_to_works: "بازگشت به آثار",
    works_all_works: "همه آثار",
    works_live_website: "وب‌سایت زنده",
    works_view_project: "مشاهده پروژه",
    works_visit_project: "مشاهده پروژه",
    works_cta_live: "زنده",
    works_view_on_foundation: "مشاهده در Foundation",
    works_explore: "کاوش",
    works_close: "بستن",
    works_next: "بعدی",
    works_previous: "قبلی",
    works_character_study: "۰۱ / ۰۱ · مطالعه کاراکتر",
    works_moving_identity: "۰۱ / ۰۱ · هویت متحرک",
    works_nft_kicker: "Foundation / ۱ از ۱",
    works_nft_heading: "آن‌چین",
    works_nft_intro:
      "مجموعه‌ای از آثار دیجیتال مستقل، هرکدام با صفحه‌ی اختصاصی برای مشاهده و مینت.",
    works_project_archive: "آرشیو پروژه‌ها",
    works_selected_digital: "آثار",
    works_digital_works: "دیجیتال منتخب",
    works_archive_websites_desc:
      "آرشیوی منتخب از محصولات دیجیتال، پلتفرم‌های فرهنگی و تجربه‌های وب تعاملی.",
    works_archive_character_heading_1: "مطالعات",
    works_archive_character_heading_2: "کاراکتر",
    works_archive_character_desc:
      "کاوش شخصیت، استایل‌پردازی، سیلوئت و سیستم‌های بصری روایی.",
    works_archive_influencer_heading_1: "پرسونای",
    works_archive_influencer_heading_2: "مصنوعی",
    works_archive_influencer_desc:
      "سیستم هویت دیجیتال، توسعهٔ ظاهر مولد و تصویرسازی کمپین برای استعداد مصنوعی.",
    works_archive_nft_heading_1: "نسخه‌های",
    works_archive_nft_heading_2: "آن‌چین",
    works_archive_nft_desc:
      "نسخه‌های دیجیتال مستقل و سیستم‌های بصری کلکسیونی با لینک به صفحه مینت.",
    works_discipline: "حوزه",
    works_year_label: "سال",
    works_status_label: "وضعیت",
    works_in_development: "در حال توسعه",
    hero_dev: "توسعه‌دهنده فرانت‌اند و طراح وب خلاق",
    hero_scroll: "برای مشاهده اسکرول کنید",
    work_title: "آثار منتخب",
    about_op: "اپراتور",
    about_h1_1: "حضور",
    about_h1_2: "طراحی‌شده",
    about_intro_before: "من بابک هستم — با نام ",
    about_intro_after: ".",
    about_p2:
      "مدبک، فعالیت خلاق بابک روانبخش است؛ توسعه‌دهنده فرانت‌اند و طراح چندرشته‌ای که وب‌سایت‌های تعاملی، هویت‌های دیجیتال و تجربه‌های وب مبتنی بر موشن می‌سازد. کار او ترکیبی از رهبری خلاق، طراحی UI/UX، سیستم‌های بصری، Next.js، React، TypeScript و مهندسی مدرن فرانت‌اند است.",
    about_p3:
      "پروژه‌ها شامل طراحی و توسعه وب‌سایت، سیستم‌های کاراکتر، پرسوناهای دیجیتال مبتنی بر هوش مصنوعی و نسخه‌های بصری آن‌چین هستند — همیشه با تمرکز بر کیفیت ساخت، تعامل و زبان بصری روشن.",
    about_p4:
      "پیش‌زمینه طراحی گرافیک به ساخت رابط‌هایی کمک می‌کند که نه فقط کارآمد، بلکه ترکیب‌بندی‌شده و آمادهٔ تولید باشند.",
    about_p5:
      "مستقر در استانبول و فعال در مقیاس جهانی، مدبک برای همکاری‌های منتخب فریلنس در توسعه فرانت‌اند، طراحی وب و تجربه‌های دیجیتال خلاق آماده است.",
    about_operator_image_alt:
      "پرتره بابک روانبخش، توسعه‌دهنده فرانت‌اند خلاق با نام مدبک",
    stat_role: "نقش",
    stat_stack: "تکنولوژی",
    stat_engine: "موتور رندر",
    stat_loc: "موقعیت",
    val_role: "توسعه‌دهنده فرانت‌اند",
    val_loc: "استانبول / جهانی",
    man_defy: "شکستن",
    man_conv: "سنت‌ها",
    man_p:
      "MADBAK در تقاطع خشونت خام و دقت دیجیتال سطح بالا قرار دارد. ما معماری‌های تعاملی می‌سازیم که وب معمولی را به چالش می‌کشند.",
    man_re: "موتور رندر",
    man_phys: "فیزیک",
    man_grid: "سیستم گرید",
    man_stat: "وضعیت",
    man_aes: "زیبایی‌شناسی اسمی",
    game_proto: "پروتکل سیستم // مینی گیم",
    game_sys: "سیستم",
    game_dec: "رمزگشایی",
    game_desc1:
      "روی نود بزنید تا بسته‌ها تزریق شوند, یک اسکچ کوچک تعاملی.",
    game_desc2: "همین بود. ممنون که بازی کردید.",
    game_btn1: "تزریق",
    game_btn2: "قرار نیست اتفاق خاصی بیفته :)",
    game_tap: "سریع بزن",
    game_prog: "پیشرفت",
    game_log_1: "در حال تزریق…",
    game_log_2: "رمزگشایی…",
    game_log_3: "سیگنال دریافت شد…",
    game_access: "دسترسی تأیید شد",
    game_complete_sub: "رمزگشایی کامل شد",
    game_surprise_fail: "خطای سیستم",
    game_surprise_access: "در حال دسترسی به هسته…",
    foot_ready: "سیستم آماده است",
    foot_init: "تماس",
    foot_send: "ارسال داده",
    foot_blurb:
      "مدبک — توسعه‌دهنده فرانت‌اند و طراح وب خلاق با تمرکز بر وب‌سایت‌های تعاملی، تجربه‌های دیجیتال و پروژه‌های مبتنی بر موشن.",
    foot_explore_works: "مشاهده آثار",
    works_archive_link: "باز کردن آرشیو",
    modal_active: "مجموعه داده فعال",
    modal_type: "نوع",
    modal_year: "سال",
    modal_role: "نقش",
    modal_tech: "تکنولوژی",
    modal_context: "زمینه",
    modal_sim: "شبیه‌سازی آفلاین",
    work_sub1: "۰۴ — منتخب",
    work_sub2: "خلاقانه · نسخه‌های دیجیتال",
    work_h1: "آثار",
    work_h2: "منتخب",
    work_desc:
      "مجموعه‌ای منتخب از آثار دیجیتال , جلوه‌های بصری سطح بالا، فراداده‌های دقیق و تجربه‌های غوطه‌ور.",
    view_details: "مشاهده گالری",
    nft_sub1: "۰۵ — دارایی‌های دیجیتال",
    nft_sub2: "روی زنجیره · تایید شده",
    nft_h1: "کالکشن",
    nft_h2: "NFT",
    contact_label: "[۰۰۴] تماس",
    contact_title_1: "بیایید",
    contact_title_2: "با هم بسازیم",
    contact_commissions:
      "پذیرای پروژه‌های فریلنس و همکاری‌های خلاقانه (به‌صورت انتخابی)",
    contact_rights: "© ۲۰۲۶ MADBAK. تمامی حقوق محفوظ است.",
    contact_available: "در دسترس",
    contact_social_x: "ایکس",
    contact_social_ig: "اینستاگرام",
    contact_social_tg: "تلگرام",
    contact_social_wa: "واتساپ",
    contact_social_li: "لینکدین",
    contact_social_gh: "گیت‌هاب",
    nft_view: "مشاهده اثر",
  },
  tr: {
    header_arch: "Yaratıcı Arşiv",
    header_loc: "İstanbul Merkezli / Küresel",
    header_idx: "Endeks: 2024.11.X",
    nav_works: "Projeler",
    nav_about: "Hakkımda",
    nav_contact: "İletişim",
    nav_services: "Hizmetler",
    nav_logo_aria: "MADBAK — sayfanın başına dön",
    nav_primary_aria: "Ana gezinme",
    nav_lang_aria: "Dil",
    nav_menu_toggle: "Menü",
    nav_close_menu: "Menüyü kapat",
    nav_section_label: "Dizin",
    nav_home: "Giriş",
    nav_works_categories_aria: "Proje kategorileri",
    works_archive_crumb: "MADBAK / ARŞİV",
    works_scroll_cue: "Keşfetmek için kaydır",
    works_next_category: "Sonraki kategori",
    works_back_to_works: "Projelere dön",
    works_all_works: "Tüm projeler",
    works_live_website: "CANLI WEB SİTESİ",
    works_view_project: "Projeyi Gör",
    works_visit_project: "PROJEYİ ZİYARET ET",
    works_cta_live: "CANLI",
    works_view_on_foundation: "Foundation’da Gör",
    works_explore: "Keşfet",
    works_close: "Kapat",
    works_next: "Sonraki",
    works_previous: "Önceki",
    works_character_study: "01 / 01 · karakter çalışması",
    works_moving_identity: "01 / 01 · hareketli kimlik",
    works_nft_kicker: "Foundation / 1 of 1",
    works_nft_heading: "ON-CHAIN",
    works_nft_intro:
      "Her biri görüntüleme ve mint için kendi sayfasına sahip bağımsız dijital parçalar koleksiyonu.",
    works_project_archive: "PROJE ARŞİVİ",
    works_selected_digital: "SEÇİLİ",
    works_digital_works: "DİJİTAL PROJELER",
    works_archive_websites_desc:
      "Dijital ürünler, kültürel platformlar ve etkileşimli web deneyimlerinden oluşan seçili bir arşiv.",
    works_archive_character_heading_1: "KARAKTER",
    works_archive_character_heading_2: "ÇALIŞMALARI",
    works_archive_character_desc:
      "Karakter keşfi, stil geliştirme, siluet ve anlatısal görsel sistemler.",
    works_archive_influencer_heading_1: "SENTETİK",
    works_archive_influencer_heading_2: "PERSONA",
    works_archive_influencer_desc:
      "Sentetik yetenek için dijital kimlik sistemleri, üretken görünüm geliştirme ve kampanya görselleri.",
    works_archive_nft_heading_1: "ZİNCİR ÜSTÜ",
    works_archive_nft_heading_2: "EDİSYONLAR",
    works_archive_nft_desc:
      "Mint sayfalarına bağlı bağımsız dijital edisyonlar ve koleksiyonluk görsel sistemler.",
    works_discipline: "Disiplin",
    works_year_label: "Yıl",
    works_status_label: "Durum",
    works_in_development: "Geliştirme Aşamasında",
    hero_dev: "Yaratıcı Frontend Geliştirici ve Web Tasarımcısı",
    hero_scroll: "Keşfetmek için kaydırın",
    work_title: "Seçilmiş İşler",
    about_op: "Operatör",
    about_h1_1: "TASARLANMIŞ",
    about_h1_2: "VARLIK",
    about_intro_before: "BEN BABAK — ",
    about_intro_after: " adıyla üretiyorum.",
    about_p2:
      "Madbak, Babak Ravanbakhsh’ın yaratıcı pratiğidir; etkileşimli web siteleri, dijital kimlikler ve hareket odaklı web deneyimleri üreten bir frontend geliştirici ve çok disiplinli tasarımcıdır. Çalışmaları yaratıcı yön, UI/UX tasarımı, görsel sistemler, Next.js, React, TypeScript ve modern frontend mühendisliğini birleştirir.",
    about_p3:
      "Projeler web sitesi tasarımı ve geliştirme, karakter sistemleri, yapay zekâ destekli dijital personalar ve zincir üstü görsel edisyonları kapsar — her zaman zanaat, etkileşim ve net bir görsel dil vurgusuyla.",
    about_p4:
      "Grafik tasarım geçmişi, yalnızca işlevsel değil aynı zamanda özenle kompoze edilmiş ve üretime hazır arayüzler oluşturmasına yardımcı olur.",
    about_p5:
      "İstanbul merkezli ve küresel çalışan Madbak; frontend geliştirme, web tasarımı ve yaratıcı dijital deneyimler alanında seçili freelance iş birliklerine açıktır.",
    about_operator_image_alt:
      "Babak Ravanbakhsh’ın portresi — Madbak adıyla bilinen yaratıcı frontend geliştirici",
    stat_role: "Rol",
    stat_stack: "Teknoloji",
    stat_engine: "Render Motoru",
    stat_loc: "Konum",
    val_role: "Frontend Geliştirici",
    val_loc: "İstanbul / Küresel",
    man_defy: "Meydan Oku",
    man_conv: "GELENEKLERE",
    man_p:
      "MADBAK, ham acımasızlık ile üst düzey dijital hassasiyetin kesiştiği noktada var olur. Sıradan web'e meydan okuyan etkileşimli mimariler inşa ediyoruz.",
    man_re: "Render Motoru",
    man_phys: "Fizik",
    man_grid: "Izgara Sistemi",
    man_stat: "Durum",
    man_aes: "Estetik Nominal",
    game_proto: "Sistem Protokolü // Mini Oyun",
    game_sys: "Sistem",
    game_dec: "Şifre Çözme",
    game_desc1:
      "Paket enjekte etmek için düğmeye dokunun — küçük bir etkileşim.",
    game_desc2: "Hepsi bu kadar. İlginiz için teşekkürler.",
    game_btn1: "Enjekte Et",
    game_btn2: "Özel bir şey olmayacak :)",
    game_tap: "Hızlı Dokun",
    game_prog: "İlerleme",
    game_log_1: "Enjekte ediliyor…",
    game_log_2: "Şifre çözülüyor…",
    game_log_3: "Sinyal alındı…",
    game_access: "ERİŞİM ONAYLANDI",
    game_complete_sub: "ŞİFRE ÇÖZME TAMAMLANDI",
    game_surprise_fail: "SİSTEM HATASI",
    game_surprise_access: "ÇEKİRDEĞE ERİŞİLİYOR…",
    foot_ready: "Sistem Hazır",
    foot_init: "İletişim",
    foot_send: "Veri Gönder",
    foot_blurb:
      "Madbak — etkileşimli web siteleri, dijital deneyimler ve hareket odaklı projeler üreten yaratıcı frontend geliştirici ve web tasarımcısı.",
    foot_explore_works: "İşleri keşfet",
    works_archive_link: "Arşivi aç",
    modal_active: "Veri Seti Aktif",
    modal_type: "Tür",
    modal_year: "Yıl",
    modal_role: "Rol",
    modal_tech: "Teknoloji",
    modal_context: "Bağlam",
    modal_sim: "Simülasyon Çevrimdışı",
    work_sub1: "04 — Seçilmiş",
    work_sub2: "Yaratıcı · Dijital Sürümler",
    work_h1: "SEÇİLMİŞ",
    work_h2: "İŞLER",
    work_desc:
      "Dijital yaratımların özenle seçilmiş bir koleksiyonu — üst düzey görseller, keskin ayrıntılar ve sürükleyici deneyimler.",
    view_details: "Galeriyi Görüntüle",
    nft_sub1: "05 — Dijital Varlıklar",
    nft_sub2: "Zincir Üstü · Doğrulanmış",
    nft_h1: "NFT",
    nft_h2: "KOLEKSİYONU",
    contact_label: "[004] İLETİŞİM",
    contact_title_1: "HAYDI",
    contact_title_2: "BİRLİKTE ÜRETELİM",
    contact_commissions:
      "Seçili freelance projeler ve yaratıcı iş birlikleri için uygun",
    contact_rights: "© 2026 MADBAK. Tüm hakları saklıdır.",
    contact_available: "Şu an müsait",
    contact_social_x: "X",
    contact_social_ig: "Instagram",
    contact_social_tg: "TELEGRAM",
    contact_social_wa: "WHATSAPP",
    contact_social_li: "LinkedIn",
    contact_social_gh: "GitHub",
    nft_view: "Varlığı Görüntüle",
  },
} as const;

export type LangKey = keyof typeof TRANSLATIONS;

export const PROJECTS = [
  {
    id: "01",
    sys: "MB-X1",
    year: "2022",
    image:
      "https://pbs.twimg.com/media/GdN7WSoXQAAgQO0?format=jpg&name=large",
    images: [
      "https://pbs.twimg.com/media/GUkhZdYXMAAW-54?format=jpg&name=small",
      "https://pbs.twimg.com/media/GdN7WSoXQAAgQO0?format=jpg&name=large",
      "https://pbs.twimg.com/media/GUkhZdaXwAAdhCY?format=jpg&name=small",
      "https://pbs.twimg.com/media/GVyCuqXXMAAj73g?format=jpg&name=small",
      "https://pbs.twimg.com/media/GWak2uBXAAELrGP?format=jpg&name=medium",
    ],
    langs: {
      en: {
        title: "YOUNG MI",
        cat: "Character series",
        desc: "Character exploration, styling, and narrative visuals.",
        role: "Art direction & design",
        stack: "Digital illustration",
        context: "Character study",
      },
      fa: {
        title: "یانگ می",
        cat: "سری کاراکتر",
        desc: "اکتشاف کاراکتر، استایل و روایت بصری.",
        role: "هنر و طراحی",
        stack: "تصویرسازی دیجیتال",
        context: "مطالعه کاراکتر",
      },
      tr: {
        title: "YOUNG MI",
        cat: "Karakter serisi",
        desc: "Karakter keşfi, stil ve görsel anlatım.",
        role: "Sanat yönetimi ve tasarım",
        stack: "Dijital illüstrasyon",
        context: "Karakter çalışması",
      },
    },
  },
  {
    id: "02",
    sys: "MB-X2",
    year: "2022",
    image:
      "https://github.com/madbak98/My-image/blob/main/6fe54cd9-9cce-492c-ba0c-e6438d486fff.png?raw=true",
    images: [
      // 1 Escalator · 2 Gym selfie · 3 Airport · 4 Rooftop blue · 5 Rooftop pink
      "https://github.com/madbak98/My-image/blob/main/hf_20260218_000747_13e6678b-ebae-4047-a96d-57a325ebbf6f.png?raw=true",
      "https://github.com/madbak98/My-image/blob/main/6fe54cd9-9cce-492c-ba0c-e6438d486fff.png?raw=true",
      "https://github.com/madbak98/My-image/blob/main/hf_20260218_004459_b98c0ec6-0c6a-4a90-a28a-beb3712647cc.png?raw=true",
      "https://github.com/madbak98/My-image/blob/main/hf_20260218_000558_d245cf16-18d6-49a3-a994-a4a524d5049e.png?raw=true",
      "https://github.com/madbak98/My-image/blob/main/07c36aee-e7ba-456f-bb91-bb238e60cbf1.png?raw=true",
    ],
    langs: {
      en: {
        title: "PINK ARMY",
        cat: "AI influencer",
        desc: "Digital persona design and generative look development.",
        role: "Creative direction",
        stack: "AI-assisted pipeline",
        context: "Influencer concept",
      },
      fa: {
        title: "ارتش صورتی",
        cat: "اینفلوئنسر AI",
        desc: "طراحی پرسونا و توسعهٔ ظاهر مبتنی بر هوش مصنوعی.",
        role: "رهبری خلاق",
        stack: "خط لوله AI",
        context: "کانسپت اینفلوئنسر",
      },
      tr: {
        title: "PEMBE ORDU",
        cat: "YZ influencer",
        desc: "Dijital persona tasarımı ve üretken görünüm geliştirme.",
        role: "Yaratıcı yönetim",
        stack: "YZ destekli üretim",
        context: "Influencer konsepti",
      },
    },
  },
  {
    id: "03",
    sys: "MB-X3",
    year: "2025",
    image:
      "https://github.com/madbak98/My-image/blob/main/Gemini_Generated_Image_v6xqw8v6xqw8v6xq.png?raw=true",
    images: [
      "https://github.com/madbak98/My-image/blob/main/Gemini_Generated_Image_v6xqw8v6xqw8v6xq.png?raw=true",
      "https://github.com/madbak98/My-image/blob/main/Gemini_Generated_Image_ovdyb1ovdyb1ovdy.jpg?raw=true",
      "https://github.com/madbak98/My-image/blob/main/IMG_3225.JPG?raw=true",
    ],
    titleStack: {
      en: ["ETHEREAL", "BEINGS"],
      fa: ["موجودات", "اثیری"],
      tr: ["RUHANİ", "VARLIKLAR"],
    },
    langs: {
      en: {
        title: "ETHEREAL BEINGS",
        cat: "Cover art",
        desc: "Illustrations of celestial figures and speculative worlds.",
        role: "Illustration",
        stack: "Digital painting",
        context: "Album / cover",
      },
      fa: {
        title: "موجودات اثیری",
        cat: "کاور آرت",
        desc: "تصویرسازی شخصیت‌های آسمانی و جهان‌های فرضی.",
        role: "تصویرسازی",
        stack: "نقاشی دیجیتال",
        context: "آلبوم / کاور",
      },
      tr: {
        title: "RUHANİ VARLIKLAR",
        cat: "Kapak sanatı",
        desc: "Göksel figürler ve spekülatif dünyaların illüstrasyonu.",
        role: "İllüstrasyon",
        stack: "Dijital boyama",
        context: "Albüm / kapak",
      },
    },
  },
  {
    id: "04",
    sys: "MB-X4",
    year: "2023",
    image:
      "https://pbs.twimg.com/media/GbZStxSbIAEgwHH?format=jpg&name=large",
    images: [
      "https://pbs.twimg.com/media/GbZStxSbIAEgwHH?format=jpg&name=large",
      "https://pbs.twimg.com/media/GbZR4wrbQAAAtSn?format=jpg&name=medium",
      "https://pbs.twimg.com/media/GbZStxTbAAAydlE?format=jpg&name=medium",
      "https://pbs.twimg.com/media/GbZR4wpaIAA3Ino?format=jpg&name=medium",
      "https://pbs.twimg.com/media/GbZStxQawAA56hR?format=jpg&name=medium",
      "https://pbs.twimg.com/media/GbZR4wtbgAA92kW?format=jpg&name=medium",
    ],
    langs: {
      en: {
        title: "BATMAN X LV",
        cat: "Concept design",
        desc: "Luxury fashion meets pop iconography — visual exploration.",
        role: "Concept art",
        stack: "3D / compositing",
        context: "Fashion crossover",
      },
      fa: {
        title: "بتمن x لویی ویتون",
        cat: "طراحی کانسپت",
        desc: "تقاطع مد لوکس و نمادهای پاپ — کاوش بصری.",
        role: "آرت کانسپت",
        stack: "۳بعدی / کامپوزیت",
        context: "هم‌ارزی مد",
      },
      tr: {
        title: "BATMAN X LV",
        cat: "Konsept tasarım",
        desc: "Lüks moda ve pop ikonografisi — görsel keşif.",
        role: "Konsept sanat",
        stack: "3D / kompozit",
        context: "Moda crossover",
      },
    },
  },
  {
    id: "05",
    sys: "MB-X5",
    year: "2021",
    image:
      "https://pbs.twimg.com/media/GT3NgmXW4AAK0cW?format=jpg&name=medium",
    images: [
      "https://pbs.twimg.com/media/GQCNpfGWkAAuj_t?format=jpg&name=medium",
      "https://pbs.twimg.com/media/GQCOgSqWYAA_rP5?format=jpg&name=medium",
      "https://pbs.twimg.com/media/GQCaGcdXoAAxOBQ?format=jpg&name=medium",
    ],
    langs: {
      en: {
        title: "URBAN LEGENDS",
        cat: "Pixel art",
        desc: "Retro pixel scenes inspired by urban folklore.",
        role: "Pixel art & animation",
        stack: "Aseprite / PS",
        context: "Series",
      },
      fa: {
        title: "افسانه‌های شهری",
        cat: "پیکسل آرت",
        desc: "صحنه‌های پیکسلی الهام‌گرفته از فولکلور شهری.",
        role: "پیکسل و موشن",
        stack: "Aseprite / PS",
        context: "سری",
      },
      tr: {
        title: "ŞEHİR EFSANELERİ",
        cat: "Piksel sanatı",
        desc: "Kentsel folklordan esinlenen retro piksel sahneler.",
        role: "Piksel ve animasyon",
        stack: "Aseprite / PS",
        context: "Seri",
      },
    },
  },
  {
    id: "06",
    sys: "MB-X6",
    year: "2023",
    image:
      "https://github.com/madbak98/My-image/blob/main/A71CBD71-2336-4019-AB4E-65A920E28D27.PNG?raw=true",
    images: [
      "https://pbs.twimg.com/media/GT_QPtuX0AAEdB9?format=jpg&name=medium",
      "https://pbs.twimg.com/media/GStY8XGX0AAdgpR?format=jpg&name=medium",
    ],
    langs: {
      en: {
        title: "BACKTALK",
        cat: "Poster",
        desc: "Brutalist layout, type, and poster structure.",
        role: "Graphic design",
        stack: "Print / digital",
        context: "Poster series",
      },
      fa: {
        title: "بک‌تاک",
        cat: "پوستر",
        desc: "لی‌آوت بروتال، تایپ و ساختار پوستر.",
        role: "گرافیک",
        stack: "چاپ / دیجیتال",
        context: "سری پوستر",
      },
      tr: {
        title: "BACKTALK",
        cat: "Afiş",
        desc: "Brütalist düzen, tipografi ve afiş yapısı.",
        role: "Grafik tasarım",
        stack: "Baskı / dijital",
        context: "Afiş serisi",
      },
    },
  },
];

export const NFT_ITEMS = [
  {
    id: "01",
    sys: "FND-01",
    year: "2024",
    platform: "Foundation",
    image:
      "https://ipfs.foundation.app/ipfs/QmSawSnoD6YG6jP1ot8WhoZFcaS12tjE587y9QSJK2F1XD/nft.jpg",
    href: "https://foundation.app/mint/base/0xA19ec1c9b7d4380CcB94f2B4eCBC1af51C485577/8",
    langs: {
      en: { title: "Puffer Hustler", cat: "1/1 Edition" },
      fa: { title: "پافر هاسلِر", cat: "نسخه ۱/۱" },
      tr: { title: "Puffer Hustler", cat: "1/1 Sürüm" },
    },
  },
  {
    id: "02",
    sys: "FND-02",
    year: "2024",
    platform: "Foundation",
    image:
      "https://ipfs.foundation.app/ipfs/QmUq7LLGzhKSrLePeYu5iR2XdTWZPsaPzWWQGUkNj9fbNb/nft.png",
    href: "https://foundation.app/mint/base/0xA19ec1c9b7d4380CcB94f2B4eCBC1af51C485577/3",
    langs: {
      en: { title: "Labubu Boi", cat: "1/1 Edition" },
      fa: { title: "لابوبو بوی", cat: "نسخه ۱/۱" },
      tr: { title: "Labubu Boi", cat: "1/1 Sürüm" },
    },
  },
  {
    id: "03",
    sys: "FND-03",
    year: "2024",
    platform: "Foundation",
    image:
      "https://ipfs.foundation.app/ipfs/QmRomE5hbmiPUaRz8Yuqd7Mi9kDGrA93MkeEaCQdLu6icM/nft.jpg",
    href: "https://foundation.app/mint/base/0xA19ec1c9b7d4380CcB94f2B4eCBC1af51C485577/26",
    langs: {
      en: { title: "Court Phantom", cat: "1/1 Edition" },
      fa: { title: "کورت فانتوم", cat: "نسخه ۱/۱" },
      tr: { title: "Court Phantom", cat: "1/1 Sürüm" },
    },
  },
  {
    id: "04",
    sys: "FND-04",
    year: "2024",
    platform: "Foundation",
    image:
      "https://ipfs.foundation.app/ipfs/QmZKuxDhcmrFMmLGnjrELXF4y6sFvjjvL6jHZ8M22CkkNX/nft.png",
    href: "https://foundation.app/mint/base/0xA19ec1c9b7d4380CcB94f2B4eCBC1af51C485577/4",
    langs: {
      en: { title: "Matcha Hood", cat: "1/1 Edition" },
      fa: { title: "ماچا هود", cat: "نسخه ۱/۱" },
      tr: { title: "Matcha Hood", cat: "1/1 Sürüm" },
    },
  },
  {
    id: "05",
    sys: "FND-05",
    year: "2024",
    platform: "Foundation",
    image:
      "https://ipfs.foundation.app/ipfs/QmZRGEXyzMW5uZVM9whZ34R8TizGWL4hN7yeajxnk12djG/nft.png",
    href: "https://foundation.app/mint/base/0xA19ec1c9b7d4380CcB94f2B4eCBC1af51C485577/9",
    langs: {
      en: { title: "Snack Bandit", cat: "1/1 Edition" },
      fa: { title: "اسنک بندیت", cat: "نسخه ۱/۱" },
      tr: { title: "Snack Bandit", cat: "1/1 Sürüm" },
    },
  },
  {
    id: "06",
    sys: "FND-06",
    year: "2024",
    platform: "Foundation",
    image:
      "https://ipfs.foundation.app/ipfs/QmTafSoJ8Hj754nkiNZ7rEYHT4uiRdkJPmvGJkiYQTRwiC/nft.jpg",
    href: "https://foundation.app/mint/base/0xA19ec1c9b7d4380CcB94f2B4eCBC1af51C485577/11",
    langs: {
      en: { title: "Gummy Shooter", cat: "1/1 Edition" },
      fa: { title: "گامی شوتر", cat: "نسخه ۱/۱" },
      tr: { title: "Gummy Shooter", cat: "1/1 Sürüm" },
    },
  },
];

/**
 * Social profiles — edit here, or set in `.env.local`:
 * `NEXT_PUBLIC_SOCIAL_*` overrides below.
 */
export const SOCIAL_LINKS = {
  instagram:
    process.env.NEXT_PUBLIC_SOCIAL_INSTAGRAM ??
    "https://www.instagram.com/madbak98/",
  x: process.env.NEXT_PUBLIC_SOCIAL_X ?? "https://x.com/Lilosama98",
  telegram:
    process.env.NEXT_PUBLIC_SOCIAL_TELEGRAM ?? "https://t.me/Lilosaama",
  whatsapp:
    process.env.NEXT_PUBLIC_SOCIAL_WHATSAPP ?? "https://wa.me/905010050395",
  linkedin:
    process.env.NEXT_PUBLIC_SOCIAL_LINKEDIN ??
    "https://www.linkedin.com/in/babak-ravanbakhsh-16535a327/",
  github:
    process.env.NEXT_PUBLIC_SOCIAL_GITHUB ?? "https://github.com/madbak98",
} as const;

export const CONTACT_EMAIL = "madbak98@gmail.com";
